language: python
dist: xenial
apt:
  packages:
  - libatlas-base-dev
  - libharminv-dev
  - libgsl-dev
  - libmeep-mpi-default-dev
  - libmeep-mpi-default
  - hdf5-tools
  - h5utils
  - libhdf5-openmpi-dev
  - libhdf5-serial-dev
python:
- '3.6'
notifications:
  email: false
    
before_install:
- sudo apt-get update -qq
install:
- pip install -r meep_tomo/requirements.txt
- pip install pytest
- pip install coverage
- pip install coveralls
- pip freeze
script:
- coverage run --source=meep_tomo -m pytest
- coverage report -m
after_success:
- coveralls --verbose

